name: chrome_travis
homepage: https://github.com/tekartik/chrome_travis.dart
description: travis-ci scripts for chrome
version: 0.3.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  args: ">=2.6.0"

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  dev_test: ">=1.0.0+4"
  build_test: any
  build_runner: ">=2.4.13"
  pedantic:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
